<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up(): void {
  Schema::table('users', function(Blueprint $t){ $t->string('username')->unique(); $t->string('role')->default('Siswa'); $t->foreignId('kelas_aktif_id')->nullable(); $t->string('status_kehadiran')->default('hadir'); $t->timestamp('last_login_at')->nullable(); });
  Schema::create('jurusans',fn(Blueprint $t)=>[$t->id(),$t->string('nama_jurusan'),$t->string('kode_jurusan',10)->unique(),$t->timestamps()]);
  Schema::create('rombels',fn(Blueprint $t)=>[$t->id(),$t->string('nama_rombel',20),$t->timestamps()]);
  Schema::create('kelas_aktifs',function(Blueprint $t){$t->id();$t->unsignedSmallInteger('tingkat');$t->foreignId('jurusan_id')->constrained('jurusans');$t->foreignId('rombel_id')->constrained('rombels');$t->string('nama_kelas');$t->timestamps();$t->unique(['tingkat','jurusan_id','rombel_id']);});
  Schema::table('users',fn(Blueprint $t)=>$t->foreign('kelas_aktif_id')->references('id')->on('kelas_aktifs')->nullOnDelete());
  Schema::create('mata_pelajarans',fn(Blueprint $t)=>[$t->id(),$t->string('kode_mapel',20)->unique(),$t->string('nama_mapel'),$t->timestamps()]);
  Schema::create('paket_soals',function(Blueprint $t){$t->id();$t->foreignId('mata_pelajaran_id')->constrained('mata_pelajarans');$t->foreignId('pembuat_user_id')->constrained('users');$t->string('judul');$t->string('status')->default('draft');$t->timestamps();});
  Schema::create('bank_soals',function(Blueprint $t){$t->id();$t->foreignId('paket_soal_id')->constrained('paket_soals')->cascadeOnDelete();$t->unsignedInteger('urutan');$t->string('tipe_soal')->default('PG');$t->text('pertanyaan');$t->string('gambar_url')->nullable();$t->decimal('bobot_nilai',7,2)->default(1);$t->timestamps();$t->unique(['paket_soal_id','urutan']);});
  Schema::create('opsi_jawabans',function(Blueprint $t){$t->id();$t->foreignId('bank_soal_id')->constrained('bank_soals')->cascadeOnDelete();$t->string('kode',1);$t->text('teks_opsi');$t->boolean('is_benar')->default(false);$t->timestamps();$t->unique(['bank_soal_id','kode']);});
  Schema::create('master_ujians',function(Blueprint $t){$t->id();$t->string('judul');$t->foreignId('paket_soal_id')->constrained('paket_soals');$t->boolean('acak_soal')->default(false);$t->boolean('acak_opsi')->default(false);$t->boolean('tampilkan_nilai_akhir')->default(false);$t->string('hasil_visibilitas')->default('manual');$t->timestamp('tanggal_rilis_hasil')->nullable();$t->timestamps();});
  Schema::create('jadwal_ujians',function(Blueprint $t){$t->id();$t->foreignId('master_ujian_id')->constrained('master_ujians');$t->timestamp('waktu_mulai');$t->timestamp('waktu_selesai');$t->unsignedInteger('durasi_menit');$t->boolean('gunakan_token')->default(false);$t->string('token',20)->nullable();$t->timestamps();});
  Schema::create('jadwal_ujian_kelas',function(Blueprint $t){$t->foreignId('jadwal_ujian_id')->constrained('jadwal_ujians')->cascadeOnDelete();$t->foreignId('kelas_aktif_id')->constrained('kelas_aktifs')->cascadeOnDelete();$t->primary(['jadwal_ujian_id','kelas_aktif_id']);});
  Schema::create('sesi_ujians',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained('users')->cascadeOnDelete();$t->foreignId('jadwal_ujian_id')->constrained('jadwal_ujians');$t->timestamp('waktu_login');$t->timestamp('waktu_submit')->nullable();$t->string('status')->default('aktif');$t->string('ip_address',45)->nullable();$t->json('device_info')->nullable();$t->decimal('nilai_akhir',7,2)->nullable();$t->timestamp('last_seen_at')->nullable();$t->timestamps();$t->unique(['user_id','jadwal_ujian_id']);});
  Schema::create('sesi_ujian_soals',function(Blueprint $t){$t->id();$t->foreignId('sesi_ujian_id')->constrained('sesi_ujians')->cascadeOnDelete();$t->foreignId('bank_soal_id')->constrained('bank_soals');$t->unsignedInteger('nomor_soal');$t->json('opsi_order')->nullable();$t->boolean('ditandai')->default(false);$t->unique(['sesi_ujian_id','nomor_soal']);});
  Schema::create('jawaban_siswas',function(Blueprint $t){$t->id();$t->foreignId('sesi_ujian_id')->constrained('sesi_ujians')->cascadeOnDelete();$t->foreignId('bank_soal_id')->constrained('bank_soals');$t->foreignId('opsi_jawaban_id')->nullable()->constrained('opsi_jawabans');$t->text('jawaban_essay')->nullable();$t->string('tipe_soal');$t->decimal('skor',7,2)->default(0);$t->string('scoring_status')->default('auto_scored');$t->decimal('skor_manual',7,2)->nullable();$t->text('komentar')->nullable();$t->foreignId('dinilai_oleh_user_id')->nullable()->constrained('users');$t->timestamp('tanggal_dinilai')->nullable();$t->timestamp('client_updated_at')->nullable();$t->timestamps();$t->unique(['sesi_ujian_id','bank_soal_id']);});
  Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('sesi_ujian_id')->nullable()->constrained('sesi_ujians')->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('action');$t->foreignId('bank_soal_id')->nullable()->constrained('bank_soals');$t->json('payload')->nullable();$t->string('ip_address',45)->nullable();$t->timestamps();});
  Schema::create('session_events',function(Blueprint $t){$t->id();$t->foreignId('sesi_ujian_id')->constrained('sesi_ujians')->cascadeOnDelete();$t->string('event_type');$t->json('event_data')->nullable();$t->timestamps();});
 }
 public function down(): void { foreach(['session_events','audit_logs','jawaban_siswas','sesi_ujian_soals','sesi_ujians','jadwal_ujian_kelas','jadwal_ujians','master_ujians','opsi_jawabans','bank_soals','paket_soals','mata_pelajarans'] as $table) Schema::dropIfExists($table); Schema::table('users',fn(Blueprint $t)=>$t->dropForeign(['kelas_aktif_id'])); Schema::dropIfExists('kelas_aktifs');Schema::dropIfExists('rombels');Schema::dropIfExists('jurusans');Schema::table('users',fn(Blueprint $t)=>$t->dropColumn(['username','role','kelas_aktif_id','status_kehadiran','last_login_at'])); }
};