@extends('layouts.app')
@section('standalone', true)
@section('title','Lembar Ujian CBT - SMKN 1 Blora')
@section('content')
<style>
body{background:#f1f5f9;user-select:none}.exam-topbar{background:#fff;border-bottom:2px solid #e2e8f0;box-shadow:0 2px 10px rgba(0,0,0,.02);padding:.8rem 0;position:sticky;top:0;z-index:1020}.timer-box{background:#fee2e2;color:#dc2626;font-weight:700;font-size:1.2rem;padding:.45rem 1.1rem;border-radius:8px;border:1px solid #fca5a5;display:inline-block}.question-card,.grid-card{background:#fff;border-radius:12px;box-shadow:0 4px 15px rgba(0,0,0,.03)}.question-card{min-height:60vh}.question-badge{background:#1e3a8a;color:#fff;padding:.42rem 1rem;border-radius:20px;font-weight:600;font-size:.86rem}.question-text{font-size:1.12rem;color:#1e293b;line-height:1.65}.option-input{display:none}.option-label{display:block;padding:1rem 1.15rem;border:2px solid #e2e8f0;border-radius:10px;margin-bottom:.8rem;cursor:pointer;transition:.2s;color:#334155}.option-label:hover{border-color:#94a3b8;background:#f8fafc}.option-input:checked+.option-label{border-color:#1e3a8a;background:#eff6ff;color:#1e3a8a;font-weight:500}.option-letter{display:inline-grid;place-items:center;width:30px;height:30px;border-radius:50%;background:#e2e8f0;margin-right:10px;font-weight:700}.option-input:checked+.option-label .option-letter{background:#1e3a8a;color:#fff}.grid-container{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.grid-btn{aspect-ratio:1;border:1px solid #cbd5e1;background:#fff;border-radius:8px;font-weight:700;color:#475569}.grid-btn.answered{background:#10b981;border-color:#059669;color:#fff}.grid-btn.flagged{background:#f59e0b;border-color:#d97706;color:#fff}.grid-btn.active{outline:3px solid #1e3a8a;outline-offset:2px}.sync-indicator{position:fixed;right:18px;bottom:18px;z-index:1050}.save-state{font-size:.76rem}.flag-box{padding:.75rem 1rem;background:#fffbeb;border:1px solid #fde68a;border-radius:9px}.modal-content{border:0;border-radius:16px}.modal-custom-header{background:#1e3a8a;color:#fff;border-radius:16px 16px 0 0}
</style>
<div class="exam-topbar"><div class="container-fluid px-4"><div class="row align-items-center"><div class="col-4 d-none d-md-block"><h5 class="mb-0 fw-bold">{{ $question->tipe_soal === 'PG' ? 'Pilihan Ganda' : 'Isian Singkat' }}</h5><small class="text-secondary">CBT SMKN 1 Blora</small></div><div class="col-12 col-md-4 text-center"><div class="timer-box"><i class="fa-regular fa-clock me-1"></i><span id="timer">00:00:00</span></div><div id="save-status" class="save-state text-muted mt-1">Siap</div></div><div class="col-4 d-none d-md-flex justify-content-end align-items-center"><div class="text-end me-3"><strong>{{ auth()->user()->name }}</strong><div class="text-muted small">{{ auth()->user()->username }}</div></div><button type="button" id="fullscreen" class="btn btn-light border text-dark"><i class="fa-solid fa-expand"></i></button></div></div></div></div>
<div class="container-fluid px-3 px-md-4 py-4"><div class="row"><div class="col-lg-8 mb-4"><div class="question-card p-3 p-md-4 d-flex flex-column"><div class="d-flex justify-content-between align-items-center mb-4 border-bottom pb-3"><span class="question-badge">Soal {{ $number }} / {{ $items->count() }}</span><span class="badge bg-secondary">{{ $question->tipe_soal === 'PG' ? 'Pilihan Ganda' : 'Isian Singkat' }}</span></div><div class="mb-4"><div class="question-text mb-3">{{ $question->pertanyaan }}</div>@if($question->gambar_url)<img src="{{ $question->gambar_url }}" class="img-fluid rounded border shadow-sm" style="max-height:300px" alt="Gambar soal">@endif</div>
<form method="POST" id="answer-form" class="d-flex flex-column flex-grow-1">@csrf<input type="hidden" name="soal_hash" value="{{ $encode($question->id) }}"><input type="hidden" name="next_number" id="next" value="{{ $number }}"><input type="hidden" name="client_updated_at" id="client-updated-at">
@if($question->tipe_soal==='PG')<div class="flex-grow-1">@foreach($options as $o)<input class="option-input" id="opsi-{{ $o->id }}" type="radio" name="opsi_hash" value="{{ $encode($o->id) }}" @checked(optional($saved)->opsi_jawaban_id===$o->id)><label class="option-label" for="opsi-{{ $o->id }}"><span class="option-letter">{{ $o->kode }}</span>{{ $o->teks_opsi }}</label>@endforeach</div>@else<textarea class="form-control flex-grow-1" rows="6" name="essay" placeholder="Ketik jawaban Anda di sini...">{{ optional($saved)->jawaban_essay }}</textarea>@endif
<label class="flag-box mt-3"><input id="flag" class="me-2" type="checkbox" @checked($item->ditandai)> <i class="fa-solid fa-flag text-warning me-1"></i> Tandai soal untuk ditinjau kembali</label><div class="d-flex justify-content-between mt-4 pt-3 border-top"><button formaction="/ujian/sesi/{{ $sessionHash }}/simpan" onclick="next.value={{ max(1,$number-1) }}" @disabled($number===1)><i class="fa-solid fa-chevron-left"></i> Sebelumnya</button>@if($number<$items->count())<button formaction="/ujian/sesi/{{ $sessionHash }}/simpan" onclick="next.value={{ $number+1 }}">Simpan & Lanjut <i class="fa-solid fa-chevron-right"></i></button>@else<button type="button" class="bg-success" data-bs-toggle="modal" data-bs-target="#submit-modal"><i class="fa-solid fa-flag-checkered"></i> Selesai Ujian</button>@endif</div></form></div></div>
<div class="col-lg-4"><aside class="grid-card p-4"><h6 class="fw-bold mb-3 border-bottom pb-2">Navigasi Soal</h6><div class="grid-container mb-4">@foreach($items as $x)<button class="grid-btn {{ $x->nomor_soal===$number?'active':'' }} {{ $answers->has($x->bank_soal_id)?'answered':'' }} {{ $x->ditandai?'flagged':'' }}" form="answer-form" formaction="/ujian/sesi/{{ $sessionHash }}/simpan" onclick="next.value={{ $x->nomor_soal }}">{{ $x->nomor_soal }}</button>@endforeach</div><div class="small p-3 bg-light border rounded"><div class="mb-2"><i class="fa-solid fa-square text-success me-2"></i>Sudah dijawab</div><div class="mb-2"><i class="fa-regular fa-square me-2"></i>Belum dijawab</div><div><i class="fa-solid fa-flag text-warning me-2"></i>Ditandai</div></div><button type="button" class="danger w-100 mt-3" data-bs-toggle="modal" data-bs-target="#submit-modal"><i class="fa-solid fa-check-double"></i> Selesai Ujian</button></aside></div></div></div>
<div class="modal fade" id="submit-modal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header modal-custom-header"><h5 class="modal-title fw-bold"><i class="fa-solid fa-clipboard-check me-2"></i>Konfirmasi Selesai</h5><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body p-4"><p>Apakah Anda yakin ingin mengakhiri ujian? Pastikan jawaban telah diperiksa.</p><div class="alert alert-warning small mb-0"><i class="fa-solid fa-circle-info me-1"></i> Jawaban lokal akan disinkronkan sebelum submit diproses.</div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary text-dark bg-white" data-bs-dismiss="modal">Cek Kembali</button><button form="answer-form" formaction="/ujian/sesi/{{ $sessionHash }}/selesai" class="bg-success">Ya, Selesai Ujian</button></div></div></div></div>
<div class="sync-indicator"><div id="offline-badge" class="badge bg-danger p-3 shadow rounded-pill" style="display:none"><i class="fa-solid fa-wifi-slash me-2"></i>Offline - antrean lokal: <span id="pending-count">0</span></div></div>
<script>
let remaining={{ $remaining }};const sessionId='{{ $sessionHash }}',csrf='{{ csrf_token() }}',form=document.getElementById('answer-form'),badge=document.getElementById('offline-badge'),pendingCount=document.getElementById('pending-count'),statusEl=document.getElementById('save-status'),timer=document.getElementById('timer');let debounce,submitted=false;
function renderTimer(){const value=Math.max(0,remaining),h=Math.floor(value/3600),m=Math.floor(value%3600/60),s=value%60;timer.textContent=[h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}renderTimer();
setInterval(()=>{remaining--;renderTimer();if(remaining<=0&&!submitted){submitted=true;form.action='/ujian/sesi/{{ $sessionHash }}/selesai';form.submit()}},1000);
const dbp=new Promise((ok,fail)=>{const r=indexedDB.open('cbt-offline',1);r.onupgradeneeded=()=>r.result.createObjectStore('answers',{keyPath:'key'});r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)});
async function allPending(){const db=await dbp;return new Promise(ok=>{const r=db.transaction('answers').objectStore('answers').getAll();r.onsuccess=()=>ok(r.result.filter(x=>x.session_id===sessionId))})}
async function queueCurrent(){const f=new FormData(form),stamp=new Date().toISOString();document.getElementById('client-updated-at').value=stamp;const row={key:sessionId+':'+f.get('soal_hash'),session_id:sessionId,soal_hash:f.get('soal_hash'),opsi_hash:f.get('opsi_hash'),essay:f.get('essay'),client_updated_at:stamp};const db=await dbp;db.transaction('answers','readwrite').objectStore('answers').put(row);await renderOffline();return row}
async function clearPending(rows){const db=await dbp,tx=db.transaction('answers','readwrite');rows.forEach(x=>tx.objectStore('answers').delete(x.key))}
async function renderOffline(){const q=await allPending();badge.style.display=(!navigator.onLine||q.length)?'block':'none';pendingCount.textContent=q.length}
async function syncPending(){const q=await allPending();if(!navigator.onLine||!q.length)return;statusEl.textContent='Menyimpan...';try{const r=await fetch('/ujian/sesi/{{ $sessionHash }}/sync',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({answers:q})});if(r.ok){await clearPending(q);statusEl.textContent='Tersimpan otomatis';await renderOffline()}else statusEl.textContent='Menunggu sinkronisasi'}catch{statusEl.textContent='Offline';await renderOffline()}}
function autosave(){clearTimeout(debounce);debounce=setTimeout(async()=>{await queueCurrent();await syncPending()},350)}
document.querySelectorAll('input[name=opsi_hash],textarea[name=essay]').forEach(x=>x.addEventListener(x.tagName==='TEXTAREA'?'input':'change',autosave));
document.getElementById('flag').addEventListener('change',e=>fetch('/ujian/sesi/{{ $sessionHash }}/flag',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({soal_hash:'{{ $encode($question->id) }}',ditandai:e.target.checked})}));
document.getElementById('fullscreen').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());
setInterval(()=>fetch('/ujian/sesi/{{ $sessionHash }}/ping',{method:'POST',headers:{'X-CSRF-TOKEN':csrf}}),15000);
document.addEventListener('visibilitychange',()=>{if(document.hidden)fetch('/ujian/sesi/{{ $sessionHash }}/event',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({event_type:'tab_switch'})})});
window.addEventListener('offline',async()=>{await queueCurrent();statusEl.textContent='Offline';await renderOffline();fetch('/ujian/sesi/{{ $sessionHash }}/event',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({event_type:'offline_detected'})}).catch(()=>{})});
window.addEventListener('online',()=>{syncPending();fetch('/ujian/sesi/{{ $sessionHash }}/event',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({event_type:'back_online'})})});renderOffline();syncPending();
</script>
@endsection
